import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/components/TopNav";
import SideNav from "@/components/SideNav";
import { montserrat } from "@/theme/fonts";
import ADS from "@/components/ADS";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <TopNav />
        <div className="flex justify-between pt-36 container">
          <div className="w-1/5">
            <div className="fixed top-36 w-56 flex flex-col gap-12">
              <SideNav />
              <ADS />
            </div>
          </div>
          <div className="w-3/4 h-auto ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
